version: '2'
services:
  my_cv_api-app:
    image: my_cv_api
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://my_cv_api-postgresql:5432/my_cv_api
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  my_cv_api-postgresql:
    extends:
      file: postgresql.yml
      service: my_cv_api-postgresql
