version: '2'
services:
  my_cv_api-postgresql:
    image: postgres:11.3
    # volumes:
    #     - ~/volumes/jhipster/my_cv_api/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=my_cv_api
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
